apiVersion: v1
kind: Namespace
metadata:
  name: nginx-fleet
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: rancher-fleet-test-apps-nginx
    meta.helm.sh/release-namespace: nginx-fleet
